stores:
  yaml:
    indent: 2
  json:
    indent: 2
  json_binary:
    indent: 2
keys:
  - &example-key age18u6m67xg08y688megulc9xfeg79y4r2wvh8x0sxkcd9agazw9pds2u73kk
creation_rules:
  - path_regex: '[^\/]+\.(yaml|json|env|ini)$'
    key_groups:
    - age:
      - *example-key
